version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672

  message-analyzer:
    image: application/message-analyzer:simple
    container_name: 'message-analyzer'
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 20s
      retries: 3
    environment:
      - server_port=8080
      - spring_rabbitmq_host=rabbitmq
    ports:
      - 8084:8080

  medical-monitoring:
    image: application/medical-monitoring:simple
    container_name: 'medical-monitoring'
    depends_on:
      message-analyzer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 20s
      retries: 3
    environment:
      - server_port=8080
      - spring_rabbitmq_host=rabbitmq
    ports:
      - 8081:8080

  person-service:
    image: application/person-service:simple
    container_name: 'person-service'
    depends_on:
      message-analyzer:
        condition: service_healthy
      medical-monitoring:
        condition: service_healthy
    healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
       interval: 10s
       timeout: 20s
       retries: 3
    environment:
      - server_port=8080
    ports:
      - 8082:8080